name: Deploy Core API to Azure App Service

on:
  workflow_run:
    workflows: ["Backend CI (Build, Test & Analyze)"]
    types:
      - completed
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure (Core API)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Download artifact from CI job
        uses: actions/download-artifact@v4
        with:
          name: api-app 
          run-id: ${{ github.event.workflow_run.id }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06CA4A04193C45C1BFDB2D14681EB597 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F63489E157184C80A665EDDC7DD2EC1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2DBFE6844D834F2AB17B9AC6A4A91D05 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e-mechanic-core-api'
          slot-name: 'Production'
          package: .