name: Deploy Notification Service to Azure App Service

on:
  workflow_run:
    workflows: ["Backend CI (Build, Test & Analyze)"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure (Notification Service)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Download artifact from CI job
        uses: actions/download-artifact@v4
        with:
          name: notification-app
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_434B5221E07B4598908C0FF56566EE22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_161A37481E0546DB809D4A7B9914EC14 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81A644C379F64495AA29A04F72324039 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "e-mechanic-notification-service-api"
          slot-name: "Production"
          package: .