name: Deploy Notification Service to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "src/eMechanic.Backend/Services/src/eMechanic.NotificationService.API/**"
      - ".github/workflows/deploy-notification-service.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build and Package Notification Service
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore src/eMechanic.Backend/eMechanic.sln

      - name: Build Notification Service Project
        run: dotnet build src/eMechanic.Backend/Services/src/eMechanic.NotificationService.API/eMechanic.NotificationService.API.csproj --configuration Release --no-restore

      - name: Publish Notification Service Project
        run: dotnet publish src/eMechanic.Backend/Services/src/eMechanic.NotificationService.API/eMechanic.NotificationService.API.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: notification-app
          path: ./publish

  deploy:
    name: Deploy to Azure (Notification Service)
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: notification-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_434B5221E07B4598908C0FF56566EE22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_161A37481E0546DB809D4A7B9914EC14 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81A644C379F64495AA29A04F72324039 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "e-mechanic-notification-service-api"
          slot-name: "Production"
          package: .
